# Generated by Django 4.0.3 on 2022-03-21 16:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('details', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_post', to='area.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='area.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('bs_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bs_email', models.EmailField(max_length=50)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='area.area')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='area.profile')),
            ],
        ),
    ]
