# Generated by Django 4.0.3 on 2022-03-22 07:01

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='area.profile'),
        ),
        migrations.AlterField(
            model_name='area',
            name='hoodimage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
