# Generated by Django 4.0.3 on 2022-03-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_alter_area_admin_alter_area_hoodimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood_post', to='area.area'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='area.profile'),
        ),
    ]
